Dockerfile
docker-compose.development.yml
docker-compose.yml

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/9
Relates to:
- https://github.com/icefoganalytics/elcc-data-management/pull/73/files
Using the pattern developed in the elcc-data-management project, make sure that all app components use UTC by default.
Time related data should only be converted to the User's timezone at the last minute, when displaying the data.
:clock3: Enforce UTC in back-end in development and production modes.
1. Boot the app via `dev up`
2. Check the app loads at http://localhost:8080

Standardize Timezone Handling To UTC

---

api/package-lock.json
api/package.json
api/src/middlewares/jwt-middleware.ts
api/src/router.ts
docker-compose.development.yml
web/src/App.vue
web/src/api/http-client.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/10
See https://github.com/icefoganalytics/travel-authorization/issues/151
**Describe the bug**
Go to this file `api/tsconfig.json` and see that it is showing as errored. This error doesn't seem to have any effect, but it has the potential to hide meaningful errors and creates noise when developing.
```
Cannot find type definition file for 'express-unless'.
The file is in the program because:
Entry point for implicit type library 'express-unless'
```
Solution is likely to upgrade express-jwt. See https://github.com/auth0/express-jwt/issues/307
**Screenshots**
Upgrade express-jwt to fix tsconfig.json error.
Upgrade jwks-rsa to match example from documentation.
Use type casting to make jwksRsa work with express-jwt as per …

Fix tsconfig.json Error Around `express-unless`

---

README.md
api/jest.config.ts
api/package-lock.json
api/package.json
api/src/config.ts
api/src/serializers/datasets/table-helpers/determine-access.ts
api/tests/tsconfig.json
api/tsconfig.json
docker-compose.yml
web/src/api/status-api.ts
web/src/components/datasets/NewDatasetForm.vue
web/src/config.ts

Add ability to build app in production mode and log in.
Break `tsconfig.json` test config from production `tsconfig.json`
Integrate configs inline for front-end.
2. Check that VS Code correctly loads @ paths in `api/tests/utils/deep-pick.test.ts`
3. Boot the app via `dc up --build`
4. Log in to the app at http://localhost:8080, this will create
5. Open your database editor and go to the `idp_production` database.
6. Change your user's role to "system_admin" and save the change.
7. Update your user's first/last name and position as needed.
8. From the /dashboard page click the "Sync user groups" button.
9. Create a dataset.

Fixup: Local Production Build Environment

---

.vscode/settings.json
api/.eslintrc.cjs
api/package-lock.json
api/package.json
docker-compose.development.yml
web/.eslintrc.cjs
web/package-lock.json
web/package.json
web/tsconfig.json

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/30
Set up Eslint in the front-end. This helps ensure consistency across the codebase.
It also make development easier, since it highlights certain kinds of errors that are hard to find normally.
Note that I'm hoisting the .gitignore and .prettier.yaml so they get loaded as well. They are one level higher to match the external setup, so the paths make sense when read.
1. Lint a file like `web/src/pages/DatasetsPage.vue` via 
```sh
dev web npm run lint web/src/pages/DatasetsPage.vue
````
2. Move `@click="refresh"` above any other attribute, check that you get a lint error after this.

Dev Tooling: Enable Eslint for Front-End

---

api/src/controllers/index.ts
api/src/controllers/taggings-controller.ts
api/src/controllers/tags-controller.ts
api/src/models/tagging.ts
api/src/router.ts
api/src/services/index.ts
api/src/services/taggings/create-service.ts
api/src/services/taggings/destroy-service.ts
api/src/services/taggings/index.ts
web/src/api/taggings-api.ts
web/src/api/tags-api.ts
web/src/components/SaveStateProgress.vue
web/src/components/datasets/DataDescriptionFormCard.vue
web/src/components/datasets/OwnerNotesFormCard.vue
web/src/components/datasets/SubjectFormCard.vue
web/src/components/tags/TagsCombobox.vue
web/src/use/use-taggings.ts
web/src/use/use-tags.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/28
Relates to:
- https://github.com/icefoganalytics/internal-data-portal/issues/7
- [0001, Data Modeling, 2024-01-05](https://docs.google.com/document/d/1Mdbl_Cy0BgKiq0DGdvOKUqJn-FdgbF0LSVykwf__FY8/edit?pli=1)
- [0002, UI Modeling, 2024-01-08](https://docs.google.com/document/d/1tP63Ob4XPBGlASPHVf1GnNb3hlIkybmWBqJDA61u3J0/edit)
The edit version of the pages doesn’t seem to exist in the wireframes, so I would need another layer of User Role components to handle the different viewer types if I build this out. It might make more sense to just use auto-save for everything.
Various tabs on the same level as this component.
* /datasets/:id - GET 
* /datasets/:id - PATCH, update data set
* /tags - GET, list tags
* /tags - POST, …

Part 3: Data Owner: Edit an Existing Dataset - Add Keywords and Owner Notes

---

README.md
docker-compose.development.yml
web/src/config.ts

Switch Auth0 Client Id to Project Specific One
Update client id to new auth0 client id.
4. Create a new user such as `marlen+idp+user@icefoganalytics.com.
> I used the pattern `email+project-acronym+user-role@domain.com

Switch Auth0 Client Id to Project Specific One

---

api/src/controllers/qa-scenarios/add-random-access-requests-controller.ts
api/src/db/migrations/2024.03.07T00.26.44.add-sync-failure-at-concept-to-users-table.ts
api/src/middlewares/authorization-middleware.ts
api/src/models/user.ts
api/src/serializers/datasets/show-serializer.ts
api/src/serializers/user-serializers.ts
api/src/services/user-groups/yukon-government-directory-sync-service.ts
api/src/services/users/create-service.ts
api/src/services/users/index.ts
api/src/services/users/yukon-government-directory-sync-service.ts
api/tests/factories/user-factory.ts
web/src/App.vue
web/src/components/PageLoader.vue
web/src/components/user-groups/UserGroupAutocomplete.vue
web/src/pages/UnauthorizedPage.vue
web/src/router.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/51
When login in as a user that doesn't match up with the Yukon Government directory, it creates a user that is missing their `groupMembership` record.
All users should have a groupMembership record created when the user is create.
Probably the quickest solution is to move the user creation logic from `findOrCreateUserFromAuth0Token` into a service that does these things. It will likely also need to load all users groups from YG if there aren't any. If there are user groups, it should assign a random group.
In the long run, and if this looks easy, I should move the user creation logic out of the authorization pipeline.
Currently _any_ API call could potentially create a User object as a side effect, and this is obviously …

Handle Users That Don't Exist In Yukon Government Directory

---

web/src/components/access-grants/AccessGrantDeleteDialog.vue
web/src/components/access-requests/AccessRequestApproveDialog.vue
web/src/components/access-requests/AccessRequestDenyDialog.vue
web/src/components/access-requests/AccessRequestRevokeDialog.vue
web/src/components/dataset-fields/DatasetFieldDeleteDialog.vue
web/src/components/datasets/DataDescriptionCard.vue
web/src/components/datasets/OwnerCard.vue
web/src/components/datasets/SubjectCard.vue
web/src/components/users/UserAttributeTextField.vue

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/52
See https://github.com/icefoganalytics/travel-authorization/issues/154#issuecomment-1960295021
Add lock icon to all read-only text and select fields.
Did not add lock icon to read-only checkbox fields as I'm not sure what UI to use.
New
Old
4. Navigate around the app and note that all readonly text and select fields have lock icons in them.

Make all Readonly Fields in the App Use a mdi-lock prepend-icon

---

api/src/controllers/access-requests-controller.ts
api/src/models/access-request.ts
api/src/policies/access-requests-policy.ts
api/tests/policies/access-requests-policy.test.ts
web/src/api/access-requests-api.ts
web/src/api/datasets-api.ts
web/src/components/dashboard-widgets/MyDataCard.vue
web/src/components/dashboard-widgets/MyRequestsCard.vue
web/src/components/dashboard-widgets/MySubscriptionsCard.vue
web/src/components/dashboards/DataOwnerDashboard.vue
web/src/components/datasets/DatasetsTable.vue
web/src/use/use-access-requests.ts
web/src/use/use-datasets.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/58
Relates to:
- [0001, Data Modeling, 2024-01-05](https://docs.google.com/document/d/1Mdbl_Cy0BgKiq0DGdvOKUqJn-FdgbF0LSVykwf__FY8/edit?pli=1)
- [0002, UI Modeling, 2024-01-08](https://docs.google.com/document/d/1tP63Ob4XPBGlASPHVf1GnNb3hlIkybmWBqJDA61u3J0/edit)
Looking through the requirements, it likely makes sense to break the dashboard up into a DatasetEditorPage view and a DatasetConsumerPage view.
* /datasets - table view with search support
* /datasets/new - create new dataset page
* /datasets?where[...]
* Filter by tags/keywords
* Filter by department
* filter by ownership
* /access-requests?where[...] - filter by ownership
* /access-requests/approve - POST
* /access-requests/deny - POST
* `BaseLayout.vue`
* app …

Part 2: Dashboard Pages (Per-Role)

---

web/src/components/datasets/OwnerFormCard.vue

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/78
The owner region on the dataset description "manage" page has a save button and the other regions don't have saves (well they have the circle icon on the top).  From a user perspective I might think that the owner save button will save everything on the page.  I am not sure if it requires a different interaction or something.  But it would be nice if it could be consistent with the rest of the page.
Make the owner form card use auto-save like the rest of the page.
New auto-save for "owner" section.
Note that this also shows off a new bug: https://github.com/icefoganalytics/internal-data-portal/issues/79
Old Pre-auto-save "owner" section"
2. Boot the app via `dev …

UX: Harmonize Dataset Description Manage Owner Section To Use AutoSave Instead of Using a Save Button

---

api/src/controllers/users-controller.ts
api/src/controllers/users/search-controller.ts
api/src/models/user.ts
web/src/api/users-api.ts
web/src/components/datasets/OwnerFormCard.vue
web/src/components/users/UserSearchableAutocomplete.vue
web/src/use/use-user.ts
web/src/use/use-users.ts
web/src/use/use-vuetify-slot-names-pass-through.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/79
**Describe the bug**
When "managing" the dataset description tab, the "owner" section shows ids for owner and support information when there are more than 10 users, and the id of the user isn't returned from the back-end.
This is also caused by the owner/support person referring to a delete user - a user with the deleted_at flag set.
The endpoint should probably have the ability to override this for read and edit mode.
**Expected behavior**
The user dropdowns should always include user information and not ids.
**Screenshots**
**Additional context**
File in questions is `web/src/components/datasets/OwnerFormCard.vue`.
The various user lookup fields should be converted to back-end search and should _always_ include the …

BUG: Dataset Description Manage Owner Section Displaying Ids Instead Of Text

---

web/src/components/datasets/DatasetsTable.vue
web/src/pages/DatasetNewPage.vue
web/src/pages/DatasetsPage.vue

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/72
Would be good to add the add data button to the all data grid to allow data owners to quickly create a dataset without having to navigate back to the dashboard.
Add button.
Update new dataset page breadcrumbs to point to all datasets page.
Update Datasets Page
Updated Breadcrumbs
4. Click the "Browse all data" button in the Data Search panel.
5. Click the new "Add dataset" button to go to the new dataset form.
6. Click the new "all dataset" breadcrumb to go back to the all datasets page.

Add Dataset Button to All Datasets Page

---

api/src/controllers/datasets-controller.ts
api/src/services/datasets/update-service.ts
web/src/components/datasets/NewDatasetForm.vue
web/src/components/users/UserSearchableAutocomplete.vue

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/71
Relates to:
- https://github.com/icefoganalytics/internal-data-portal/pull/81
After the first create (register) of a dataset it takes the user to the manage screens to enter the rest of the information. I filled out all the the information top to bottom. Then navigated away as it looks to have an autosave when I navigated away the first region hadn't saved but the other regions (Subject, Owner notes) had. If I navigate back to the description tab and re-enter it seems to save fine.
Every UI action after the first auto-save of the dataset "details" section would result in broken UI behaviour.
I believe the source of the bug was a crash in the page JS due to the datasets API endpoint for update not returning an …

BUG: Terms of Use Region Does Not Save on First Entry

---

api/src/controllers/dataset-entries-controller.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/86
**Is your feature request related to a problem? Please describe.**
When a user downloads a csv from the application the export is named something like "Export, Dataset Entries, 2024-03-29".  If the user downloaded a different dataset it would have a similiar name.  Potentially be confusing when they download a lot and go to use it.
**Describe the solution you'd like**
Can the download be renamed Dataset name - date or something more descriptive  eg. Buildings-2024-03-29.
Pull datasetId from query, and use it to load dataset, and fetch dataset name for CSV download.
4. Create a dataset …

Download CSV Name Dataset Name

---

web/src/components/datasets/DatasetsTable.vue
web/src/components/tags/TagsAutocomplete.vue
web/src/use/use-datasets.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/85
**Is your feature request related to a problem? Please describe.**
When a user does a keyword search on the main dashboard it takes them to the data page with the data limited to the search.  In the search field it says click to clear or remove query. 
**Describe the solution you'd like**
I think it would be more user friendly to include the search in this field.  In the picture above it should show "buildings"
Implement a minimal search on the datasets page using the keyword search from the dashboard.
New minimal search
4. From the dashboard, enter some keywords in the datasets search, …

Search Box Populate With Dashboard Keyword

---

api/package-lock.json
api/package.json
api/src/controllers/dataset-integrations-controller.ts
api/src/controllers/datasets/download-controller.ts
api/src/controllers/datasets/index.ts
api/src/db/migrations/2024.04.03T23.02.01.add-metadata-fields-to-dataset-integrations-table.ts
api/src/middlewares/body-authorization-hoist-middleware.ts
api/src/models/dataset-integration.ts
api/src/models/dataset-integrations/activate.ts
api/src/models/dataset-integrations/index.ts
api/src/policies/datasets-policy.ts
api/src/router.ts
api/src/services/dataset-integrations/create-service.ts
api/src/services/dataset-integrations/update-service.ts
api/src/services/datasets/download/create-service.ts
api/src/services/datasets/download/index.ts
api/src/services/datasets/index.ts
api/src/utils/count-deep.ts
api/src/utils/truncate-deep.ts
web/src/api/dataset-integrations-api.ts
web/src/components/dataset-entries/DatasetEntriesTable.vue
web/src/components/dataset-entries/DownloadAsCsvButton.vue
web/src/components/dataset-fields/DatasetFieldCreateDialog.vue
web/src/components/dataset-integrations/DatasetIntegrationUpdateForm.vue
web/src/components/datasets/DataDescriptionFormCard.vue
web/src/components/users/UserAttributeTextField.vue
web/src/pages/DatasetIntegrationManagePage.vue
web/src/pages/DatasetIntegrationNewPage.vue
web/src/router.ts

Relates to:
- [0003, IDP and Storing Data, 2024-03-27](https://docs.google.com/document/d/1S6BPUqVuYNLXMOXME36os2i0LnrpRyCmWE5ihXqGix0/edit#heading=h.f4pmdcovj4q5)
- Partially completes https://github.com/icefoganalytics/internal-data-portal/issues/92
Amalgamating data from various sources in a consistent way comes with several caveats in regards to data normalization and storage. 
Currently the data portal is doing a full import of an external dataset and this may not scale well, or add much value to end users.
End users will use the platform to gain a quick preview of the dataset, and get an example of data quality. If they want more data, or a real-time interaction with the dataset, they will interact with the source dataset directly.
* Total dataset size (Bytes)
* Total number of …

Part 1: Implement Improvements Developed in Meeting On 2024-03-27

---

api/src/controllers/access-requests-controller.ts
api/src/controllers/dataset-entries-controller.ts
api/src/controllers/dataset-fields-controller.ts
api/src/controllers/datasets-controller.ts
api/src/controllers/users-controller.ts
api/src/controllers/users/search-controller.ts
api/src/models/dataset-entry.ts
api/src/policies/README.md
api/src/policies/access-requests-policy.ts
api/src/policies/base-policy.ts
api/src/policies/dataset-entries-policy.ts
api/src/policies/dataset-fields-policy.ts
api/src/policies/datasets-policy.ts
api/tests/controllers/dataset-entries-controller.test.ts
api/tests/policies/access-requests-policy.test.ts
api/tests/policies/dataset-fields-policy.test.ts
api/tests/policies/datasets-policy.test.ts
web/src/api/dataset-entries-api.ts
web/src/components/dataset-entries/DatasetEntriesTable.vue
web/src/components/datasets/DataDescriptionCard.vue
web/src/use/use-dataset-entries.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/101
Relates to:
- https://github.com/sequelize/sequelize/issues/17337
**Is your feature request related to a problem? Please describe.**
This code pattern does not work:
```ts
const where = this.query.where as WhereOptions<AccessRequest>
const filters = this.query.filters as Record<string, unknown>
const scopedAccessRequests = AccessRequestsPolicy.applyScope(AccessRequest, this.currentUser)
let filteredAccessRequests = scopedAccessRequests
if (!isEmpty(filters)) {
Object.entries(filters).forEach(([key, value]) => {
filteredAccessRequests = filteredAccessRequests.scope({ method: [key, value] })
})
}
const totalCount = await filteredAccessRequests.count({ where })
const accessRequests = await …
```

Fix Scope Chaining Usage In Controllers

---

api/src/db/migrations/2024.06.07T00.36.14.clean-user-group-names.ts
api/src/models/user-groups.ts
api/src/services/user-groups/sync-service.ts
docker-compose.development.yml
web/.eslintrc.cjs
web/package-lock.json
web/package.json
web/src/config.ts
web/src/utils/acronymize.ts
web/tests/jsconfig.json
web/tests/utils/acronymize.test.ts
web/tsconfig.eslint.json
web/tsconfig.json
web/vite.config.js

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/104
Some of my datasets weren't rendering in the All Datasets page. It turned out this was due do the acronym generator crashing because some user-group names ended with trailing whitespace.
Fix running production build locally.
Set up front-end test suite.
Clean new user group names when they come in.
Clean old user group names via migration.
4. Go to http://localhost:8080/datasets?perPage=10&page=1, and check that I can now see datasets where Department: `Economic Development` -> Division `Corporate Services`

Fix Datasets Table Render Crash From Bad Acronym

---

docker-compose.development.yml

Fixes #117 
The health check in the `docker-compose.development.yml` will fail due to new changes to `mcr.microsoft.com/mssql/server`
- Use mssql version 2022-CU13-ubuntu-22.04 to keep healthcheck working
- Removed docker-compose version as its obsolete (https://docs.docker.com/reference/compose-file/version-and-name/)
1. Remove any docker images and/or containers associated with `internal-data-portal-db-1`
2. Run `dev up`
3. Should build as normal

Fix for db healthcheck with old mssql version

---

api/src/db/migrations/2025.05.14T18.16.53.update-auth0-subject-uniquness-to-permit-nulls.ts
api/src/models/user.ts

Fixes https://github.com/icefoganalytics/internal-data-portal/issues/121
**Describe the bug**
When attempting to add a new second user to the Internal Data Portal (IDP), the creation fails with a `Failed to create` error message.
**To Reproduce**
Steps to reproduce the behavior:
1. Log in as a system admin role user.
2. Select "All Users" from the top right kebab menu.
3. Click the "Create User" button in the top right of the table.
4. Fill in user details.
3. Click Create.
4. Create a second user.
**Expected behavior**
Second user should create successfully.
**Screenshots**
**Additional context**
Issue related to the unique constraint on the auth0_subject field.
Newly created users have `null` Auth0 subject, and the unique constraint only permitted one of these.
Cause: bad AI info, …

Issue 121: Unable To Create User Second User
